language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pxinghao/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true pxinghao/react-test npm run test -- --coverage

after_success:
  - docker build -t pxinghao/multi-client ./client
  - docker build -t pxinghao/multi-nginx  ./nginx
  - docker build -t pxinghao/multi-server ./server
  - docker build -t pxinghao/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push pxinghao/multi-client
  - docker push pxinghao/multi-nginx
  - docker push pxinghao/multi-server
  - docker push pxinghao/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket-name: "elasticbeanstalk-ap-southeast-1-943926308797"
  bucket-path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
